name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Branch Name
        id: branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets[env.BRANCH_NAME == 'main' && 'MAIN_GCP_SA_KEY' || 'DEV_GCP_SA_KEY'] }}
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          
      - name: Configure gcloud CLI
        run: |          
          gcloud config set project ${{ env.BRANCH_NAME }}-pohlmanprotean-website
          gcloud config set run/region europe-west1
          gcloud auth configure-docker gcr.io

      # Enable required APIs
      - name: Enable Google Container Registry
        run: |
          gcloud services enable containerregistry.googleapis.com

      - name: Enable Google Cloud Build
        run: |
          gcloud services enable cloudbuild.googleapis.com

      - name: Enable Artifact Registry
        run: |
          gcloud services enable artifactregistry.googleapis.com

      - name: Enable Cloud Run Admin API
        run: |
          gcloud services enable run.googleapis.com

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ env.BRANCH_NAME }}-pohlmanprotean-website/${{ env.BRANCH_NAME }}-pohlmanprotean-website-image -f pohlmanprotean.se/Dockerfile pohlmanprotean.se

      - name: Push Docker image to Google Container Registry
        run: |          
          docker push gcr.io/${{ env.BRANCH_NAME }}-pohlmanprotean-website/${{ env.BRANCH_NAME }}-pohlmanprotean-website-image

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${{ env.BRANCH_NAME }}-pohlmanprotean-website \
            --image gcr.io/${{ env.BRANCH_NAME }}-pohlmanprotean-website/${{ env.BRANCH_NAME }}-pohlmanprotean-website-image \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated