name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - dev
      - main

jobs:
  execute-code-quality-validation:
    uses: ./.github/workflows/validate.yml
    with:
      branches: "main"
      eslint-enable: true
      unit-test-enable: false
      unit-test-command: npm run test
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  execute-release:
    needs: execute-code-quality-validation
    uses: ./.github/workflows/release.yml
    with:
      branches: "${{ github.ref_name }}"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
  deploy:

    needs: execute-release
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set Branch Name
        id: branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set Latest Tag
        id: set_latest_tag
        run: |
          echo "LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
          echo "Latest tag is ${{ env.LATEST_TAG }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets[env.BRANCH_NAME == 'main' && 'MAIN_GCP_SA_KEY' || 'DEV_GCP_SA_KEY'] }}
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          
      - name: Configure gcloud CLI
        run: |
          gcloud config set project ${{ env.BRANCH_NAME }}-pohlmanprotean-website
          gcloud config set run/region europe-west1
          gcloud auth configure-docker gcr.io

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ env.BRANCH_NAME }}-pohlmanprotean-website/${{ env.BRANCH_NAME }}-pohlmanprotean-website-image:${{ env.LATEST_TAG }} -f Dockerfile .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/${{ env.BRANCH_NAME }}-pohlmanprotean-website/${{ env.BRANCH_NAME }}-pohlmanprotean-website-image:${{ env.LATEST_TAG }}
      - name: Replace dots in tag for Cloud Run
        run: echo "REVISION_TAG=$(echo ${{ env.LATEST_TAG }} | sed 's/\./-/g')" >> $GITHUB_ENV
      
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${{ env.BRANCH_NAME }}-pohlmanprotean-website \
          --image gcr.io/${{ env.BRANCH_NAME }}-pohlmanprotean-website/${{ env.BRANCH_NAME }}-pohlmanprotean-website-image:${{ env.LATEST_TAG }} \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated \
          --update-env-vars "EMAIL_APP_PASS=${{ secrets.EMAIL_APP_PASS }},EMAIL_TO=${{ secrets.EMAIL_TO }},EMAIL_USER=${{ secrets.EMAIL_USER }}" \
          --tag ${{ env.REVISION_TAG }}