name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DEV_GCP_SA_KEY }}
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
      
      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/dev-pohlmanprotean-website/dev-pohlmanprotean-website-image dev-pohlmanprotean.se

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy dev-pohlmanprotean-website \
            --image gcr.io/dev-pohlmanprotean-website/dev-pohlmanprotean-website-image \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
