name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1  # Update to the latest version
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/pohlmanprotean-website/pohlmanprotean-website-image pohlmanprotean.se

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy pohlmanprotean-website \
            --image gcr.io/pohlmanprotean-website/pohlmanprotean-website-image \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
