name: Prep Google Cloud With Required Infrastructure

# Trigger this workflow manually with inputs for branch and project name
on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Google Cloud Project name (e.g., dev-my-project or main-my-project)'
        required: true
        default: 'dev-my-project'
      customer_name:
        description: 'Select the customer'
        required: true
        type: choice
        options:
          - pohlmanprotean
          - hosandrej
      branch:
        description: 'Select branch (e.g., dev or main)'
        required: true
        type: choice
        options:  
          - dev
          - main

jobs:
  prep-gcloud:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Branch Name
        id: branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Step to set the credentials_json based on the branch
      - name: Set Google Cloud Credentials
        run: |
          if [ "${{ github.event.inputs.branch }}" == "main" ]; then
            echo "CREDENTIALS_JSON=${{ secrets.MAIN_GCP_SA_KEY }}" >> $GITHUB_ENV
          else
            echo "CREDENTIALS_JSON=${{ secrets.DEV_GCP_SA_KEY }}" >> $GITHUB_ENV
        shell: bash

      - name: Prepare Google Cloud Infrastructure
        uses: Ridvan-bot/workflows/.github/workflows/prep-gcloud.yml@main
        with:
          project_name: ${{ github.event.inputs.project_name }}
          customer_name: ${{ github.event.inputs.customer_name }}
          branch: ${{ github.event.inputs.branch }}
        secrets:
          token: ${{ secrets.GH_TOKEN }}
          credentials_json: ${{ env.CREDENTIALS_JSON }}
