name: Trigger Semantic Release

on:
    workflow_call:
        inputs:
            branches:
                required: true
                type: string
jobs:
    execute-semantic-release:
        uses: ridvan-bot/workflows/.github/workflows/semantic-release.yaml@dev
        with:
            branches: ${{ inputs.branches }}