name: Trigger Semantic Release

on:
  workflow_call:
    inputs:
      branches:
        required: true
        type: string
      repo_path:
        required: true
        type: string
        default: '/pohlmanprotean.se/'
    secrets:
      token:
        required: true

jobs:
  # Early exit job to complete workflow if branches is not "dev"
  No-release:
    if: ${{ inputs.branches != 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: No release
        run: echo "Branch is not dev, no need to release."

  # Execute semantic release only if branches is "dev"
  execute-semantic-release:
    if: ${{ inputs.branches == 'main' }}
    uses: ridvan-bot/workflows/.github/workflows/semantic-release.yaml@dev
    with:
      branches: ${{ inputs.branches }}
      repo_path: ${{ inputs.repo_path }}
    secrets:
      token: ${{ secrets.token }}
