name: Trigger Semantic Release

on:
  workflow_call:
    inputs:
      branches:
        required: true
        type: string
    secrets:
      token:
        required: true
      slack_webhook:
        required: false
jobs:
  # Early exit job to complete workflow if branches is not "main"
  No-release:
    if: ${{ inputs.branches != 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: No release
        run: echo "Branch is not main, no need to release."

  # Execute semantic release only if branches is "main"
  execute-semantic-release:
    if: ${{ inputs.branches == 'main' }}
    uses: Ridvan-bot/workflows/.github/workflows/semantic-release.yml@main
    with:
      branches: "${{ inputs.branches }}"
    secrets:
      token: ${{ secrets.GH_TOKEN }}  # Pass the GH_TOKEN as 'token' to release.yml
 
  semantic-release-success:
    if: ${{ needs.execute-semantic-release.result == 'success' }}
    needs: execute-semantic-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}