name: Trigger Semantic Release

on:
  workflow_call:
    inputs:
      branches:
        required: true
        type: string
      repo_path:
        required: true
        type: string
        default: '/pohlmanprotean.se/'
    secrets:
      token:
        required: true
jobs:
  # Early exit job to complete workflow if branches is not "dev"
  No-release:
    if: ${{ inputs.branches != 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: No release
        run: echo "Branch is not dev, no need to release."

  # Execute semantic release only if branches is "dev"
  execute-semantic-release:
    if: ${{ inputs.branches == 'dev' }}
    uses: Ridvan-bot/workflows/.github/workflows/semantic-release.yml@dev
    with:
      branches: "${{ github.ref_name }}"
      repo_path: 'pohlmanprotean.se/'
    secrets:
      token: ${{ secrets.GH_TOKEN }}  # Pass the GH_TOKEN as 'token' to release.yml
