name: Prep Google Cloud With Required Infrastructure

# Trigger this workflow manually with inputs for branch and project name
on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Google Cloud Project name (e.g., dev-my-project or main-my-project)'
        required: true
        default: 'dev-my-project'
      customer_name:
        description: 'Select the customer'
        required: true
        type: choice
        options:
          - pohlmanprotean
          - hosandrej
      branch:
        description: 'Select branch (e.g., dev or main)'
        required: true
        type: choice
        options:  
          - dev
          - main

jobs:
  prep-gcloud:
    uses: Ridvan-bot/workflows/.github/workflows/prep-gcloud-.yml@main
    with:
      project_name: ${{ github.event.inputs.project_name }}
      customer_name: ${{ github.event.inputs.customer_name }}
      branch: ${{ github.event.inputs.branch }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

